export const FETCH_SINGLE_START = 'FETCH_SINGLE_START';
export const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
export const FETCH_SINGLE_FAIL = 'FETCH_SINGLE_FAIL';

export const RESET_FETCH_SINGLE = 'RESET_FETCH_SINGLE';

export const FETCH_YEARWISE_START = 'FETCH_YEARWISE_START';
export const FETCH_YEARWISE_SUCCESS = 'FETCH_YEARWISE_SUCCESS';
export const FETCH_YEARWISE_FAIL = 'FETCH_YEARWISE_FAIL';

export const RESET_FETCH_YEARWISE = 'RESET_FETCH_YEARWISE';

export const FETCH_ALL_START = 'FETCH_ALL_START';
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS';
export const FETCH_ALL_FAIL = 'FETCH_ALL_FAIL';

export const RESET_FETCH_ALL = 'RESET_FETCH_ALL' ;